### ISSUE TITLE
Record background?

### ISSUE THREAD

**Issue by jp1017** [adrielcafe/AndroidAudioRecorder#12]
I want record background in service without any Views.

May I?

**Comment by adrielcafe** [comment]
Unfortunately not at the moment 😕 

Since you don't need any Activity/View you can use the [OmRecorder](https://github.com/kailash09dabhi/OmRecorder) and take a look at  [this app](https://github.com/robinvanemden/BabyApp/blob/8743522bebd644dfcb92005d6644dbca38e84313/app/src/main/java/com/hollandhaptics/babyapp/BabyService.java) to accomplish that.

Please let me know if I can help more

**Comment by jp1017** [comment]
:+1: 

Wooooow! You're so cooooooooooool.
